#!/usr/bin/env bash
# check ip linked to domain

subs=("www" "lb-01" "web-01" "web-02")

get_ip(){
	dom=$(echo $1 | cut -d '.' -f 1)
	data=$(dig $1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v sd="$dom" '{print "The subdomain "sd" is a "$4" record and points to "$5}')
	echo $data
}
if [ $# -eq 1 ];then
	for i in ${subs[@]};
	do
		get_ip "$i.$1"
	done
elif [ $# -eq 2 ];then
	get_ip "$2.$1"
fi
