#!/usr/bin/env bash

ssh ubuntu@104.196.50.234 -i ~/.ssh/school
mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys
chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys
echo ssh-rsa ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface]                                                                  
           [-b bind_address] [-c cipher_spec] [-D [bind_address:]port]                                                     
           [-E log_file] [-e escape_char] [-F configfile] [-I pkcs11]                                                      
           [-i identity_file] [-J [user@]host[:port]] [-L address]                                                         
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]                                                
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]                                                     
           [-w local_tun[:remote_tun]] destination [command] 
